### ISSUE TITLE
In Youtube and Periscope example separator blinks and then hide

### ISSUE THREAD

**Issue by hammyhamza** [xmartlabs/XLActionController#2]

**Comment by m-revetria** [comment]
@hammyhamza thanks for your report!

The issue here is that the collection view's cells are not correctly rendered some times, there is a margin of one pixel among them and this let you see the dark background behind them (action controller's backgroundView). This happens when animating the collection view frame when presenting it.

PR #3 solves the problem in the very specific cases of Youtube and Periscope examples by overlapping cells 1 one pixel each over other. In these case doesn't matter the first pixel of each cell, so you won't notice the difference on screen. 

This workaround could be applied on other similar action controllers but I didn't include this change on the library's core because it could break some other cases (eg: cells with a separator line at top).

@mtnbarreto what do you think?

**Comment by hammyhamza** [comment]
Thanks for the workaround its working perfect. And this library is awesome.

**Comment by tudormunteanu** [comment]
Issue closed by pull request never merged. Odd.
