### ISSUE TITLE
Segues not performing correctly

### ISSUE THREAD

**Issue by ameyavichare** [xmartlabs/XLActionController#20]
When I click on one of the skypeController cells where I have added a segue, it will perform the segue to another view controller but come back again in like 1 sec

**Comment by m-revetria** [comment]
@ameyavichare, I think the issue here is that the actions' handlers are executed immediately after the user touches an action. So, the segue is performed and after a short time the action controller is dismissed. Is that the problem that you are reporting?

XLActionController's behavior should be the same of UIAlertController by default, in which, the actions' handlers are executed after the alert is dismissed. This could break some existing app using it in this way, but it's the correct behavior and could prevent future issues.

I'll take care of this in these days
