### ISSUE TITLE
Gap at bottom of menu on iPhone X

### ISSUE THREAD

**Issue by qtbeee** [xmartlabs/XLActionController#91]
XLActionController version: 4.0.1
Xcode version: 9.4
Swift 4
Using iPhone X on simulator with iOS 11.4

I noticed this empty gap between the menu and the bottom of the screen on iPhone X.
![looks weird](https://user-images.githubusercontent.com/15256678/41179994-952b078a-6b21-11e8-8792-589ba88bca45.png)

I know it's due to safe area insets, but I think it looks a bit weird. Does anyone know a way to make it look like this?
![looks weird](https://user-images.githubusercontent.com/15256678/41180490-4b383aba-6b23-11e8-83ee-2d7a57d4b49e.png)

**Comment by m-revetria** [comment]
Hi @qtbeee,

This is by design. We've followed native Action Sheet behavior in iPhone X, see this example in the Contacts app:

![image](https://user-images.githubusercontent.com/4791678/41427614-def1262c-6fdd-11e8-9b52-f4470da2f5be.png)

If you want to cover the bottom gap with a view, you can create your own custom ActionController and add a subview to the collection view. You can follow [Twitter example](https://github.com/xmartlabs/XLActionController/blob/master/Example/CustomActionControllers/Twitter.swift#L95) as guide.

![image](https://user-images.githubusercontent.com/4791678/41427936-eb085d6c-6fde-11e8-9145-0bfef8a4f6f2.png)

**Comment by qtbeee** [comment]
Sounds good, thanks.

**Comment by balazs630** [comment]
Thanks for the tip!
The Twitter example link is broken, [it's the updated one](https://github.com/xmartlabs/XLActionController/blob/master/Example/CustomActionControllers/Twitter/Twitter.swift)!
